In [1]:
import numpy as np
from numpy import linalg

In [2]:
def quadrados_minimos():
    pontos=int(input("Quantidade de pontos usados no ajuste:"))
    grau=int(input("Grau do ajuste:"))
    #Cria os vetores X e Y
    X,Y=np.zeros(pontos), np.zeros(pontos)
    for i in range(pontos):
        X[i]=float(input("x"+str(i)+"="))
        Y[i]=float(input("y"+str(i)+"="))
    #Cria vetores h
    H=np.zeros((grau+1, pontos))
    for i in range(len(H)):
        for j in range(len(H[0])):
            H[i][j]=pow(X[j],i)
    print(H)
    #Montar o sistema Ax=b
    A=np.zeros((grau+1, grau+1))
    b=np.zeros(grau+1)
    for i in range(len(A)):
        for j in range(len(A)):
            A[i][j]=H[i].dot(H[j])
        b[i]=H[i].dot(Y)
        print("A =", A)
        print()
        print("b =",b)
        #Resolver o sistema Ax=b
        x=np.linalg.solve(A,b)
        for i in range(len(x)):
            print("c"+str(i)+"=",x[i])

In [4]:
quadrados_minimos()

Quantidade de pontos usados no ajuste: 5
Grau do ajuste: 4
x0= 20
y0= 0.99907
x1= 25
y1= 0.99852
x2= 30
y2= 0.99826
x3= 35
y3= 0.99818
x4= 40
y4= 0.99828


[[1.000000e+00 1.000000e+00 1.000000e+00 1.000000e+00 1.000000e+00]
 [2.000000e+01 2.500000e+01 3.000000e+01 3.500000e+01 4.000000e+01]
 [4.000000e+02 6.250000e+02 9.000000e+02 1.225000e+03 1.600000e+03]
 [8.000000e+03 1.562500e+04 2.700000e+04 4.287500e+04 6.400000e+04]
 [1.600000e+05 3.906250e+05 8.100000e+05 1.500625e+06 2.560000e+06]]
A = [[5.00000e+00 1.50000e+02 4.75000e+03 1.57500e+05 5.42125e+06]
 [0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00]
 [0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00]
 [0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00]
 [0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00]]

b = [4.99231 0.      0.      0.      0.     ]


LinAlgError: Singular matrix